apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "chart.fullname" . }}-config'
  labels:
    app.kubernetes.io/name: '{{ include "chart.name" . }}'
data:
  ENVIRONMENT: '{{ .Values.configmap.environment | quote }}'
