apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "chart.fullname" . }}-secrets'
  labels:
    app.kubernetes.io/name: '{{ include "chart.name" . }}'
type: Opaque
data:
  api-key: '{{ .Values.secrets.apiKey | b64enc }}'
